services:
  # -----------------------------------------------------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config
      - D:\video:/video
    ports:
      - 10002:8989
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - D:\video:/video
    ports:
      - 10003:7878
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 10001:9696
    restart: unless-stopped
# -----------------------------------------------------------------------------------------------------
volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
