services:
  # -----------------------------------------------------------------------------------------------------
  sonarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr-config:/config
      - ${VIDEO_DIR}:/video
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped

  # -----------------------------------------------------------------------------------------------------
  radarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - ${VIDEO_DIR}:/video
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  prowlarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  jellyfin:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - jellyfin-config:/config
      - ${VIDEO_DIR}:/video/series
    ports:
      - ${JELLYFIN_PORT}:8096
    restart: unless-stopped
# -----------------------------------------------------------------------------------------------------
volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  jellyfin-config:
