services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS=192.168.0.99
    volumes:
      - ${FTP_FOLDER_1}:/home/vsftpd/
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    restart: unless-stopped