services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 * * * // 4am UTC
      TZ: Africa/Johannesburg
      WATCHTOWER_CLEANUP: "true"
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock