services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Removes old images to free space
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates every 24 hours (86400 sec)

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"  # Edge agent (optional)
      - "9000:9000"  # Web UI
      - "9443:9443"  # Secure Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=UTC  # Set timezone (optional)

volumes:
  portainer_data: