watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Removes old images to free space
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates every 24 hours (86400 sec)