services:
  # -----------------------------------------------------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - sonarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - radarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - jellyfin-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT}:8096
  # -----------------------------------------------------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - ${VIDEO_DIR}:/video #optional
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    volumes:
      - jellyseerr-config:/app/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYSEER_PORT}:5055
  # -----------------------------------------------------------------------------------------------------
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: on-failure
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${GLUETUN_PROVIDER}
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=${PIA_LOCATION}
      - FIREWALL_OUTBOUND_SUBNETS=${SUBNET}
    ports:
      - ${SONARR_PORT}:8989
      - ${RADARR_PORT}:7878
      - ${PROWLARR_PORT}:9696
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  # -----------------------------------------------------------------------------------------------------
volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  gluetun-data: