services:
  # -----------------------------------------------------------------------------------------------------
  sonarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - sonarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${SONARR_PORT}:8989
  # -----------------------------------------------------------------------------------------------------
  radarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - radarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${RADARR_PORT}:7878
  # -----------------------------------------------------------------------------------------------------
  prowlarr:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped
    ports:
      - ${PROWLARR_PORT}:9696
  # -----------------------------------------------------------------------------------------------------
  jellyfin:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - jellyfin-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT}:8096
  # -----------------------------------------------------------------------------------------------------
  qbittorrent:
    env_file:
      - ./.env
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - ${VIDEO_DIR}:/video #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  jellyseerr:
    env_file:
      - ./.env
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Africa/Johannesburg
    volumes:
      - jellyseerr-config:/app/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYSEER_PORT}:5055
  # -----------------------------------------------------------------------------------------------------
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr-configs:/app/data/configs
      - homarr-icons:/app/public/icons
      - homarr-data:/data
    restart: unless-stopped
    ports:
      - "${HOMARR_PORT}:7575"
  # -----------------------------------------------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Africa/Johannesburg
    restart: unless-stopped
    ports:
      - "${FLARESOLVERR_PORT}:8191"
  # -----------------------------------------------------------------------------------------------------
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true # Removes old images to free space
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates every 24 hours
      - WATCHTOWER_LABEL_ENABLE=true # Only update containers with specific labels
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  # -----------------------------------------------------------------------------------------------------
volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  homarr-configs:
  homarr-icons:
  homarr-data:
