services:
  # -----------------------------------------------------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - sonarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${SONARR_PORT}:8989
  # -----------------------------------------------------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - radarr-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${RADARR_PORT}:7878
  # -----------------------------------------------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped
    ports:
      - ${PROWLARR_PORT}:9696
  # -----------------------------------------------------------------------------------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - jellyfin-config:/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT}:8096
  # -----------------------------------------------------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - ${VIDEO_DIR}:/video #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Africa/Johannesburg
    volumes:
      - jellyseerr-config:/app/config
      - ${VIDEO_DIR}:/video
    restart: unless-stopped
    ports:
      - ${JELLYSEER_PORT}:5055
  # -----------------------------------------------------------------------------------------------------
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:2.17.0
    container_name: maintainerr
    user: 1000:1000
    volumes:
      - maintainerr-config:/opt/data
    environment:
      - TZ=Africa/Johannesburg
      - UI_PORT=${MAINTAINERR_PORT} # uncomment to change the UI port (default 6246). Useful if you're on a network where the port is already in use
    ports:
      - ${MAINTAINERR_PORT}:6246
    restart: unless-stopped
  # -----------------------------------------------------------------------------------------------------
volumes:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  homarr-configs:
  homarr-icons:
  homarr-data:
  maintainerr-config:
