services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql-config:/etc/mysql/conf.d
      - mysql-logs:/logs
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - mysql-phpmyadmin

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "UmGgkaIuBzA8TJ"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql

networks:
  mysql-phpmyadmin:

volumes:
  mysql-config:
  mysql-data:
  mysql-logs:
  mssql-volume:
