services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"  # Edge agent (optional)
      - "9000:9000"  # Web UI
      - "9443:9443"  # Secure Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=UTC  # Set timezone (optional)

volumes:
  portainer_data: